-- MySQL CDC setup for OpenCDC
CREATE USER IF NOT EXISTS 'cdc_user'@'%' IDENTIFIED BY 'cdc_pass';
GRANT REPLICATION SLAVE, REPLICATION CLIENT, SELECT ON *.* TO 'cdc_user'@'%';
GRANT SHOW DATABASES ON *.* TO 'cdc_user'@'%';
FLUSH PRIVILEGES;
